const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');

function generateScreeningPDF(screening, user, res) {
  const doc = new PDFDocument({ margin: 40 });

  // Stream output to HTTP Response
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=Skin_Health_Report_${screening.screening_id}.pdf`);
  doc.pipe(res);

  // Header Title & Logo Styling
  doc.fillColor('#0284c7').fontSize(24).text('DermAI Skin Health Screening Report', { align: 'left' });
  doc.fillColor('#64748b').fontSize(10).text('Educational AI Screening & Telemetry Document', { align: 'left' });
  doc.moveDown();

  // Horizontal Rule
  doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(40, doc.y).lineTo(570, doc.y).stroke();
  doc.moveDown();

  // Patient & Telemetry Info Box
  doc.fillColor('#0f172a').fontSize(12).text(`Patient Name: ${user.full_name || 'Valued User'}`);
  doc.text(`Patient Email: ${user.email}`);
  doc.text(`Screening Reference ID: #${screening.screening_id}`);
  doc.text(`Screening Date: ${new Date(screening.created_at || Date.now()).toLocaleString()}`);
  doc.moveDown();

  // Prediction Results Section
  doc.fillColor('#0284c7').fontSize(14).text('AI Classification Summary', { underline: true });
  doc.moveDown(0.5);

  doc.fillColor('#0f172a').fontSize(12).text(`Predicted Condition: `, { continued: true }).fillColor('#075985').text(`${screening.prediction}`);
  doc.fillColor('#0f172a').text(`AI Confidence Score: `, { continued: true }).fillColor('#0284c7').text(`${screening.confidence}%`);
  doc.fillColor('#0f172a').text(`Risk Rating: `, { continued: true })
     .fillColor(screening.risk_level === 'High' ? '#ef4444' : screening.risk_level === 'Moderate' ? '#f59e0b' : '#10b981')
     .text(`${screening.risk_level || 'Low'} Risk`);
  
  doc.moveDown();

  // Clinical Recommendation
  doc.fillColor('#0f172a').fontSize(12).text('Clinical Recommendation:');
  doc.fillColor('#334155').fontSize(10).text(screening.recommendation, { width: 500, align: 'justify' });
  doc.moveDown();

  // Draw Uploaded Lesion Image if file exists
  try {
    const fullImagePath = path.join(__dirname, '..', screening.image_path);
    if (fs.existsSync(fullImagePath)) {
      doc.text('Uploaded Lesion Telemetry Photo:');
      doc.moveDown(0.5);
      doc.image(fullImagePath, { fit: [220, 220], align: 'center' });
      doc.moveDown();
    }
  } catch (err) {
    console.error('PDF Image render error:', err);
  }

  // Educational Disclaimer Box
  doc.moveDown(2);
  doc.rect(40, doc.y, 520, 50).fillAndStroke('#fef3c7', '#f59e0b');
  doc.fillColor('#78350f').fontSize(9).text(
    'IMPORTANT MEDICAL DISCLAIMER: This report is generated by an artificial intelligence screening tool for educational purposes only. It does NOT constitute a clinical diagnosis. Always consult a qualified dermatologist.',
    50, doc.y - 42, { width: 500 }
  );

  doc.end();
}

module.exports = {
  generateScreeningPDF
};
